### ISSUE TITLE
第一名(^_^): pydantic版本要求太高，不兼容langchain 

### ISSUE THREAD

**Issue by ptonlix** [MetaGLM/zhipuai-sdk-python-v4#1]
强烈建议适配 pydantic 1.X

**Comment by acodercat** [comment]
+1

**Comment by gongfuchang** [comment]
我还写了一个适配版：https://github.com/gongfuchang/zhipuai-sdk-python-v4/blob/main/README-fix.md

**Comment by skytraveler** [comment]
不考虑对主流产品的兼容性么？这个 issue 开了一个月了。很难想象一线厂商开源支持这么差。建议加强，一两个专职跟进就好了。

**Comment by zRzRzRzRzRzRzR** [comment]
我们给langchain提供了一个pr，但是pr暂时没有通过，关于sdk问题，目前没有专门的人手在做维护，我们将抓紧跟进
