### ISSUE TITLE
什么时候能官方支持langchain呢？

### ISSUE THREAD

**Issue by ljl3937** [MetaGLM/zhipuai-sdk-python-v4#10]
什么时候能官方支持langchain呢？有没有比较好的方式使用langchain?

**Comment by emaisi** [comment]
一个不愿意主动去融入另外一种生态，另外langchain也不愿意升级pydantic版本

**Comment by upbit** [comment]
> 什么时候能官方支持langchain呢？有没有比较好的方式使用langchain?

你可以试下这个魔改的版本，只有流式API可用。适配 v2.0.1
https://github.com/upbit/StreamChatPlayground/blob/main/chat_playground/chat_zhipuai.py

**Comment by emaisi** [comment]
> > 什么时候能官方支持langchain呢？有没有比较好的方式使用langchain?
> 
> 你可以试下这个魔改的版本，只有流式API可用。适配 v2.0.1 https://github.com/upbit/StreamChatPlayground/blob/main/chat_playground/chat_zhipuai.py

好的，我学习学习一下

**Comment by upbit** [comment]
> > > 什么时候能官方支持langchain呢？有没有比较好的方式使用langchain?
> > 
> > 
> > 你可以试下这个魔改的版本，只有流式API可用。适配 v2.0.1 https://github.com/upbit/StreamChatPlayground/blob/main/chat_playground/chat_zhipuai.py
> 
> 好的，我学习学习一下

你可以参考这个版本，@gongfuchang 开源过一个。langchain新版已经处理了pydantic版本问题（自己copy了份v1），因此更新后基本就只有适配问题：
https://github.com/MetaGLM/zhipuai-sdk-python-v4/issues/1#issuecomment-1953776740

**Comment by zRzRzRzRzRzRzR** [comment]
我们给langchain官方提供了一个PR， 但是一直没有通过，这个只能等

https://github.com/langchain-ai/langchain/pull/16695

**Comment by arcstep** [comment]
情况确实有点复杂，我修改了一个比较全面的版本：

https://github.com/arcstep/langchain_zhipuai

```sh
pip install langchain_zhipu
```
