### ISSUE TITLE
ImportError: cannot import name 'ZhipuAI' from 'zhipuai'

### ISSUE THREAD

**Issue by arvinhan** [MetaGLM/zhipuai-sdk-python-v4#15]
from zhipuai import ZhipuAI
ImportError: cannot import name 'ZhipuAI' from 'zhipuai' (/usr/local/python3/lib/python3.7/site-packages/zhipuai/__init__.py)

**Comment by zRzRzRzRzRzRzR** [comment]
升级到2.0.1

**Comment by heiheiheibj** [comment]
pip uninstall zhipuai
pip install zhipuai==2.0.1.20240429 -i https://pypi.tuna.tsinghua.edu.cn/simple zhipuai

**Comment by nowayhere1** [comment]
> pip uninstall zhipuai pip install zhipuai==2.0.1.20240429 -i https://pypi.tuna.tsinghua.edu.cn/simple zhipuai

it is useless

**Comment by Stonesfromother** [comment]
> > pip uninstall zhipuai pip install zhipuai==2.0.1.20240429 -i https://pypi.tuna.tsinghua.edu.cn/simple zhipuai
> 
> it is useless

It’s ok
