### ISSUE TITLE
glm-4这里建议开一个可以上传本地图片的接口，目前是只支持在线图片的url

### ISSUE THREAD

**Issue by WildLight** [MetaGLM/zhipuai-sdk-python-v4#16]
如题，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
目前可以使用base64上传，可以查看cookbook位置

但是与OpenAI没有统一，等统一之后我们会更新sdk

**Comment by WildLight** [comment]
> 目前可以使用base64上传，可以查看cookbook位置
> 
> 但是与OpenAI没有统一，等统一之后我们会更新sdk

但是我用openai的哪种格式报错了呀
"image_url": {
					"url": f"data:image/jpg;base64,{image}"
				  }
哪请问一个用什么样的格式呢？我也试过url直接放base64的图片编码，也报错了
