### ISSUE TITLE
无法解析 print(response.choices[0].message) 繁华结构 这个是个字符串类型。还是json呀 

### ISSUE THREAD

**Issue by watchpoints** [MetaGLM/zhipuai-sdk-python-v4#19]
from zhipuai import ZhipuAI
client = ZhipuAI(api_key="") # 填写您自己的APIKey
response = client.chat.completions.create(
    model="",  # 填写需要调用的模型名称
    messages=[
        {"role": "user", "content": "你好"},
        {"role": "assistant", "content": "我是人工智能助手"},
        {"role": "user", "content": "你叫什么名字"},
        {"role": "assistant", "content": "我叫chatGLM"},
        {"role": "user", "content": "你都可以做些什么事"}
    ],
)
print(response.choices[0].message)

  **resp_json = response.json()
    resp_content = resp_json["content"]** 无法解析内容

**Comment by zRzRzRzRzRzRzR** [comment]
建议在cookbook中查看如何正确调用
