### ISSUE TITLE
API的token计算问题，简单测试用例，prompt_tokens会在2000左右

### ISSUE THREAD

**Issue by doudouwenhui** [MetaGLM/zhipuai-sdk-python-v4#2]

**Comment by doudouwenhui** [comment]
API的prompt_token计算是不是有问题？
![下载](https://github.com/zhipuai/zhipuai-sdk-python-v4/assets/20939149/3a50fd60-fc77-4566-91e8-a2dffde6b427)

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题应该已经修复，现在你可以在glm-cookbook中自己计算token的大致使用情况并进行校对
