### ISSUE TITLE
英伟达Jetson Nano无法使用zhipuai

### ISSUE THREAD

**Issue by TechWriter1984** [MetaGLM/zhipuai-sdk-python-v4#23]
1. 首先在Windows11上面，用Python写好了一个chatbot的处理逻辑，调试OK。
2. 接着想把代码移植到Jetson Nano。使用pip install可以成功安装，但是运行脚本时报错：No module named zhipuai。
3. 再次运行pip intsall或者pip install -U zhipuai，工作台提示已经成功安装。

是不是目前不支持Jetson的GPU架构？

**Comment by zRzRzRzRzRzRzR** [comment]
应该是没有arch

**Comment by glide-the** [comment]
可否使用pip show zhipuai查看下包路径 Location

![image](https://github.com/MetaGLM/zhipuai-sdk-python-v4/assets/16206043/93c73c6a-d3bc-42b4-9000-7c17a1b1e26c)

如果此命令可以看到Location信息，下方也有相关的源码文件，说明您的site-packages配置,在代码 python环境与执行pip命令的python不是同一个，请检查一些关于Location的环境变量
