### ISSUE TITLE
调用接口时传入知识库ID的接口地址是什么

### ISSUE THREAD

**Issue by mayu588** [MetaGLM/zhipuai-sdk-python-v4#32]
调用接口时传入知识库ID的接口地址是什么，我想在.net语言里面使用，因为客服不会消息，只能在这里打扰你了。

![屏幕截图 2024-05-01 194752](https://github.com/MetaGLM/zhipuai-sdk-python-v4/assets/106522613/7d589add-270d-41da-b109-24497c8981f0)

**Comment by glide-the** [comment]
> 调用接口时传入知识库ID的接口地址是什么，我想在.net语言里面使用，因为客服不会消息，只能在这里打扰你了。
> 
> ![屏幕截图 2024-05-01 194752](https://private-user-images.githubusercontent.com/106522613/327116021-7d589add-270d-41da-b109-24497c8981f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTM2ODEsIm5iZiI6MTcxNDkxMzM4MSwicGF0aCI6Ii8xMDY1MjI2MTMvMzI3MTE2MDIxLTdkNTg5YWRkLTI3MGQtNDFkYS1iMTA5LTI0NDk3Yzg5ODFmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQxMjQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTE0NTExY2MwMDA4OGNjNmEyY2NkYTQxMTVlMTdlOTU4MmQ1ODk0NTBjNjJkODA4MTE0MGEzZmYwODhiYWRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TCyZCFN83z0j7shfYffX8gZznHkGxZIm8wWnNDn2x-A)

知识库id可通过在官网的知识库栏目下创建知识库活动
![image](https://github.com/MetaGLM/zhipuai-sdk-python-v4/assets/16206043/26ac699e-d7b4-4914-ab72-50bb935f24d1)

# 另外.net中我们有集成 [C#的SDK](https://github.com/MetaGLM/zhipuai-sdk-csharp-v4?tab=readme-ov-file#/%E5%B7%A5%E5%85%B7%E8%B0%83%E7%94%A8),
