### ISSUE TITLE
support request_timeout?

### ISSUE THREAD

**Issue by yongzhuo** [MetaGLM/zhipuai-sdk-python-v4#40]
support request_timeout?

I think some scene need it, when using stream, if the first token not reponse, I can close it quickly!

**Comment by glide-the** [comment]
What to do with first token？

see readme 

client = ZhipuAI(
    timeout= httpx.Timeout(timeout=300.0, connect=8.0),
    max_retries=3,
)

**Comment by yongzhuo** [comment]
get
