### ISSUE TITLE
Why not compatible with python 3.12

### ISSUE THREAD

**Issue by CNSeniorious000** [MetaGLM/zhipuai-sdk-python-v4#45]
The latest version of `zhipuai` is marked as not-compatible with python 3.12, which is inconsistent with the `README.md`:

https://github.com/MetaGLM/zhipuai-sdk-python-v4/blob/cdfbb4fdb4f939a72ea822c948c2dbb3280364d1/README.md?plain=1#L15-L18

**Comment by glide-the** [comment]
fix version with https://github.com/MetaGLM/zhipuai-sdk-python-v4/commit/deec09d24feabedf0b5651053b4b7a62b45219ea

**Comment by CNSeniorious000** [comment]
You tagged it `20230731` 😂
