### ISSUE TITLE
多次调用后token过期

### ISSUE THREAD

**Issue by lichunown** [MetaGLM/zhipuai-sdk-python-v4#6]
代码如下:

```python
    def _generate(self, prompts: List[Dict]) -> str:
        try:
            client = ZhipuAI(api_key=self.api_key)
            response = client.chat.completions.create(model=self.model, messages=prompts, stream=False)
        except Exception as e:
            # raise e
            time.sleep(1)
            print("timeout.")
            return self._generate(prompts)
        return response.choices[0].message.content
```

多次调用该函数会导致token过期, except重试机制无法解决该问题. 

**注: ** 将`client`作为全局变量, 也无法解决问题.
 
报错提示: 

```python
zhipuai.core._errors.APIAuthenticationError: Error code: 401, with error text {"error":{"code":"1003","message":"Authorization Token已过期，请重新生成/获取。"}}
```

**Comment by Astlvk** [comment]
@lichunown 多少次可以复现？

**Comment by lichunown** [comment]
> @lichunown 多少次可以复现？

复现频次很高，基本执行2，3次就会失败一次。
我这边的复现环境是pycharm + ipython命令行终端。

由于try cache不管用，只有重启命令行环境才可以。
因此猜测会不会和`ipython`有关。

希望能尽快修复这个bug

**Comment by cybershang** [comment]
# **猜测**：或许是容器环境相关的问题

在 GitHub 的 Codespace 上跑代码时是正常的，Codespace 上用的是 Docker。
在本地虚拟机中换上 Docker 后，可以正常运行。

## 环境信息

- 物理机：Windows 
Edition	Windows 11 Pro
Version	23H2
Installed on	‎4/‎1/‎2023
OS build	22631.3235
Experience	Windows Feature Experience Pack 1000.22687.1000.0

- 虚拟机软件：VMware Workstation Pro 17

  - 虚拟机操作系统
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

  - 容器环境
podman version 4.8.3
podman-compose version 1.0.6



- 更换后的容器环境
Docker version 25.0.3 
Docker Compose version v2.23.3

## 复现用代码:

myai.py
```python
from zhipuai import ZhipuAI

class MyAI:
    def __init__(self, api_key, prompt:str) -> None:
        self.client = ZhipuAI(api_key=api_key)
        self.prompt = prompt

    def ask(self, question:str):
        response = self.client.chat.completions.create(
            model="glm-3-turbo",  # 填写需要调用的模型名称
            messages=[
                {"role": "user", "content": self.prompt},
                {"role": "user", "content": question},
            ],
        )
        return response.choices[0].message
```
main.py
```python
import debugpy
from myai import MyAI
debugpy.listen(("0.0.0.0", 5678))
print("Waiting for client to attach...")
debugpy.wait_for_client()

def main():
    robot = MyAI("API_KEY")

    while True:
        question = input("Enter your question: ")
        print(robot.ask(question))

if __name__ == "__main__":
    main()
```

**Comment by lichunown** [comment]
>  **猜测**：或许是容器环境相关的问题
> 在 GitHub 的 Codespace 上跑代码时是正常的，Codespace 上用的是 Docker。 在本地虚拟机中换上 Docker 后，可以正常运行。

**我猜测是官方的代码重复用了同一个token的问题（token过期，但没有自动更换）？**

我这边用官方提供的api方式重新封装，每次调用都是重新生成新的token，同样的环境下，没有出现上述问题。

```python
def generate_token(apikey: str, exp_seconds: int):
    try:
        id, secret = apikey.split(".")
    except Exception as e:
        raise Exception("invalid apikey", e)

    payload = {
        "api_key": id,
        "exp": int(round(time.time() * 1000)) + exp_seconds * 1000,
        "timestamp": int(round(time.time() * 1000)),
    }

    return jwt.encode(
        payload,
        secret,
        algorithm="HS256",
        headers={"alg": "HS256", "sign_type": "SIGN"},
    )


class ZhipuModel(BigModel):

    def __init__(self, api_key=None):
        super().__init__()
        if api_key is None:
            api_key = "********************"
        self.api_key = api_key

    def _generate(self, prompt: List[Dict]) -> str:
        try:
            response = requests.post('https://open.bigmodel.cn/api/paas/v4/chat/completions',
                                     headers={'Authorization': generate_token(self.api_key, 60000),
                                              'Content-Type': 'application/json'},
                                     data=json.dumps({
                                         'model': 'glm-4',
                                         # 'model': 'glm-3-turbo',
                                         'messages': prompt,
                                     }))
            print(response.content.decode('utf8'))
        except Exception as e:
            print('HTTP error: ', e)
            time.sleep(1)
            return self._generate(prompt)
        return json.loads(response.content.decode('utf8'))['choices'][0]['message']['content']
```

**Comment by zRzRzRzRzRzRzR** [comment]
这是由于鉴权只有1分钟，超过1分钟之后 就会显示过期，目前解决方案是不断重新构建client，之后我们尝试解决这个问题

**Comment by lichunown** [comment]
@zRzRzRzRzRzRzR 该bug在我这边的环境无法通过重新构建client解决，猜测有更深层的原因（可能是重新构建的时候复用了同一个token）

jwt版本：`2.8.0`
zhipuai版本：`v2.0.1`

**Comment by mmjinglin163** [comment]
同样遇到这个问题，复现步骤
1. 没有install zhipuai，直接使用执行python api.py。
2. pip install zhipuai后，重新执行python api.py，报错！
3. 更换api还是提示“Authorization Token已过期，请重新生成/获取”
4. pip install --upgrade zhipuai，仍旧提示“Authorization Token已过期，请重新生成/获取”
代码：
from zhipuai import ZhipuAI
client = ZhipuAI(api_key="") # 填写您自己的APIKey
response = client.chat.completions.create(
    model="glm-4",  # 填写需要调用的模型名称
    messages=[
        {"role": "user", "content": "作为一名营销专家，请为我的产品创作一个吸引人的slogan"},
        {"role": "assistant", "content": "当然，为了创作一个吸引人的slogan，请告诉我一些关于您产品的信息"},
        {"role": "user", "content": "智谱AI开放平台"},
        {"role": "assistant", "content": "智启未来，谱绘无限一智谱AI，让创新触手可及!"},
        {"role": "user", "content": "创造一个更精准、吸引人的slogan"}
    ],
)
print(response.choices[0].message)

**Comment by ja1496** [comment]
也许是时区问题，同步一下就可以了，我是这样做的

**Comment by mmjinglin163** [comment]
> 也许是时区问题，同步一下就可以了，我这样做
改了一下系统时间，真得就ok了。
我的现象是：在miniconda3运行py一段时间后，token过期了，重新续费后，还是提示“Authorization Token已过期，请重新生成/获取。”，重新生成token后，重启仍不生效。修改系统时间后，居然真得可以了
