### ISSUE TITLE
Embeddings API python入参有问题

### ISSUE THREAD

**Issue by Antony-Jia** [MetaGLM/zhipuai-sdk-python-v4#7]
![image](https://github.com/zhipuai/zhipuai-sdk-python-v4/assets/58219593/1e57aa17-507f-41ca-bd80-98a18570ec89)
![image](https://github.com/zhipuai/zhipuai-sdk-python-v4/assets/58219593/28598c52-16d5-44f3-9c00-e1ce7600a8f4)
代码传入问题数据出现，报告为1214 prompt 参数非法。请检查文档。

**Comment by qizhengzhong** [comment]
我也有相同的问题， 我的代码是这样的

```
from zhipuai import ZhipuAI
client = ZhipuAI(api_key=__)

def embedding():
    response = client.embeddings.create(
        model="glm-4",
        input=['test'],
    )
    embeddings = response.data[0].embedding

if __name__ == "__main__":
    embedding()```

**Comment by Congyuwang** [comment]
@zRzRzRzRzRzRzR 这个可能不是鉴权的问题哦。可能是你们embeddings API不支持List[str]，只支持str。改成str的输入就没问题，用List[str]就报1214。

**Comment by Congyuwang** [comment]
这么小个问题这么几十天还不修复

**Comment by glide-the** [comment]
多批次处理我们会在最近更新
