### ISSUE TITLE
多次调用报错APIInternalError

### ISSUE THREAD

**Issue by billfjj** [MetaGLM/zhipuai-sdk-python-v4#9]
![image](https://github.com/zhipuai/zhipuai-sdk-python-v4/assets/49382944/75e6a500-a30a-4126-81b6-96973ce0a523)
循环输入处理数据时，处理到第58张图像就会报这个错误，请问有人知道怎么解决吗

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是请求过多了，现在升级以后应该是好了，这个根SDK问题无关
